// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © kruskakli
//
//@version=6
indicator("Zebra Week", overlay=true)

show_zebra = input.bool(defval=true,  title="Show Zebra Week")

isDaily = timeframe.period == "1D"

// Get the current week number (1-53)
weekNumber = weekofyear(time)

// Check if it's an even week
isEvenWeek = weekNumber % 2 == 0

// Light gray color with 95% transparency
gee = color.new(#eeeeee, 90)

// Apply background color only on even weeks when in daily timeframe and zebra is enabled
bgcolor(title="Zebra Week", color=show_zebra and isDaily and isEvenWeek ? gee : na)
